dist: bionic

sudo: required

language: node_js

node_js:
  - 10

services:
  - xvfb

addons:
  chrome: stable

## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache: yarn

install:
  # yarn alternative to 'npm ci'
  - yarn install --frozen-lockfile

before_script:
  ## builds app and runs the 'serve' script which
  ## boots our local app server on port 5000
  ## which cypress expects to be running
  ## ---------------------------------------
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - export DISPLAY=:99.0
  - yarn lint
  - yarn build
  - yarn serve &

script:
  - yarn cy:run
