dist: bionic

sudo: required

language: node_js

node_js:
  - 10

services:
  - xvfb

addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  yarn: true
  directories:
    # need to cache folder with Cypress binary
    - ~/.cache

install:
  - yarn install

before_script:
  ## builds app and runs the 'serve' script which
  ## boots our local app server on port 5000
  ## which cypress expects to be running
  ## ---------------------------------------
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - export DISPLAY=:99.0
  - yarn lint
  - yarn build
  - yarn serve &

script:
  - yarn cy:run
